# Generated by Django 5.1.4 on 2025-02-19 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="blog_commen_created_0e6ed4_idx",
            old_name="blog_commen_created_ad0231_idx",
        ),
    ]
