# Generated by Django 5.1.4 on 2025-02-25 07:53

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
